Update OpenCoreUpdater.yml

diff --git a/.github/workflows/OpenCoreUpdater.yml b/.github/workflows/OpenCoreUpdater.yml
--- a/.github/workflows/OpenCoreUpdater.yml
+++ b/.github/workflows/OpenCoreUpdater.yml
@@ -1,4 +1,3 @@
-
 name: Download OpenCore
 
 on:
@@ -17,19 +16,19 @@ jobs:
     - name: Set up environment
       run: |
         sudo apt-get update
-        sudo apt-get install -y unzip curl zip
+        sudo apt-get install -y unzip curl zip jq
 
     - name: Fetch latest OpenCore release
       id: fetch_release
       run: |
         echo "Fetching the latest release version from GitHub..."
-        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest | grep "browser_download_url.*zip" | grep "RELEASE" | cut -d '"' -f 4)
+        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest | jq -r '.assets[] | select(.name | test("RELEASE")) | .browser_download_url')
         echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
 
     - name: Download OpenCore
       run: |
         echo "Downloading the latest version of OpenCore from $DOWNLOAD_URL..."
-        curl -L -o "OpenCore-Release.zip" "$DOWNLOAD_URL"
+        curl -L -o "OpenCore-Release.zip" "$DOWNLOAD_URL" || { echo "Download failed"; exit 1; }
 
     - name: Unzip the downloaded file
       run: |
@@ -71,10 +70,10 @@ jobs:
 
     - name: Remove unwanted drivers in EFI/OC/Drivers
       run: |
-        echo "Removing files in EFI/OC/Drivers except for OpenCanopy.efi, OpenRuntime.efi, and ResetNvramEntry.efi..."
+        echo "Removing files in EFI/OC/Drivers except for OpenCanopy.efi, OpenRuntime.efi, ResetNvramEntry.efi, OpenLinuxBoot.efi, and ToggleSipEntry.efi..."
         cd ./EFI/OC/Drivers
         for file in *; do
-          if [[ "$file" != "OpenCanopy.efi" && "$file" != "OpenRuntime.efi" && "$file" != "ResetNvramEntry.efi" && "$file" != "OpenLinuxBoot.efi" && "$file" != "ToggleSipEntry.efi"]]; then
+          if [[ "$file" != "OpenCanopy.efi" && "$file" != "OpenRuntime.efi" && "$file" != "ResetNvramEntry.efi" && "$file" != "OpenLinuxBoot.efi" && "$file" != "ToggleSipEntry.efi" ]]; then
             rm -f "$file"
           fi
         done
@@ -83,16 +82,26 @@ jobs:
     - name: Copy HfsPlus.efi to EFI/OC/Drivers
       run: |
         echo "Copying HfsPlus.efi to EFI/OC/Drivers..."
-        cp ./HfsPlus.efi ./EFI/OC/Drivers/
+        if [ -f "./HfsPlus.efi" ]; then
+          cp ./HfsPlus.efi ./EFI/OC/Drivers/
+        else
+          echo "HfsPlus.efi not found."
+          exit 1
+        fi
         
     - name: Copy ext4_x64.efi to EFI/OC/Drivers
       run: |
         echo "Copying ext4_x64.efi to EFI/OC/Drivers..."
-        cp ./Drivers/ext4_x64.efi ./EFI/OC/Drivers/
+        if [ -f "./Drivers/ext4_x64.efi" ]; then
+          cp ./Drivers/ext4_x64.efi ./EFI/OC/Drivers/
+        else
+          echo "ext4_x64.efi not found."
+          exit 1
+        fi
 
     - name: Copy SSDT-Thinkpad_X1Tablet_3Gen.aml to EFI/OC/ACPI
       run: |
-        echo "SSDT-Thinkpad_X1Tablet_3Gen.aml to EFI/OC/ACPI..."
+        echo "Copying SSDT-Thinkpad_X1Tablet_3Gen.aml to EFI/OC/ACPI..."
         cp ./ACPI/SSDT-Thinkpad_X1Tablet_3Gen.aml ./EFI/OC/ACPI/
 
     - name: Clean up
@@ -100,9 +109,9 @@ jobs:
         echo "Cleaning up..."
         rm -rf "OpenCore-Release.zip"
         rm -rf ./X64
-        rm -Rf Utilities
-        rm -Rf IA32
-        rm -Rf Docs
+        rm -rf ./Utilities  # Ensure this is correct based on your extracted content
+        rm -rf ./IA32
+        rm -rf ./Docs
         echo "OpenCore X64 EFI folder has been successfully extracted."
 
     - name: Zip the EFI directory
@@ -114,16 +123,16 @@ jobs:
       uses: actions/upload-artifact@v3
       with:
         name: Lenovo_ThinkPad_X1-Tablet_Gen3
-        path: Lenovo_ThinkPad_X1-Tablet_Gen3.zip
+        path: EFI.zip  # Ensure this matches the zipped file name
     
     - name: Upload build
       uses: svenstaro/upload-release-action@2.9.0
       if: github.event_name != 'pull_request'
       with:
-         repo_token: ${{ secrets.GITHUB_TOKEN }}
-         file: ./*.zip
-         tag: ${{ github.ref }}
-         release_name: Lenovo_ThinkPad_X1-Tablet_Gen3
-         body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
-         file_glob: true
-         overwrite: true    
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
+        file: ./EFI.zip  # Ensure this matches the zipped file name
+        tag: ${{ github.ref }}
+        release_name: Lenovo_ThinkPad_X1-Tablet_Gen3
+        body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
+        file_glob: true
+        overwrite: true
